import type { User, Class, StudentProfile } from './types';

export const MOCK_USERS: User[] = [
  { id: 'usr_admin', name: 'Admin General', email: 'admin@ritmoestudio.com', role: 'admin' },
  { id: 'usr_teacher_1', name: 'Sofia Reyes', email: 'sofia.reyes@ritmoestudio.com', role: 'teacher' },
  { id: 'usr_teacher_2', name: 'Carlos Peña', email: 'carlos.pena@ritmoestudio.com', role: 'teacher' },
  { id: 'usr_student_1', name: 'Ana Morales', email: 'ana.morales@email.com', role: 'student' },
  { id: 'usr_student_2', name: 'Luis Garcia', email: 'luis.garcia@email.com', role: 'student' },
  { id: 'usr_student_3', name: 'Elena Torres', email: 'elena.torres@email.com', role: 'student' },
  { id: 'usr_student_4', name: 'Javier Solis', email: 'javier.solis@email.com', role: 'student' },
  { id: 'usr_student_5', name: 'Maria Rodriguez', email: 'maria.rodriguez@email.com', role: 'student' },
];

export const MOCK_CLASSES: Class[] = [
  {
    id: 'cls_salsa_1',
    name: 'Salsa Nivel 1',
    description: 'Aprende los pasos básicos y el ritmo de la salsa en este curso para principiantes.',
    teacherId: 'usr_teacher_1',
    teacherName: 'Sofia Reyes',
    schedule: 'Lunes y Miércoles, 18:00 - 19:00',
    duration: 60,
    maxStudents: 20,
    level: 'principiante',
    image: 'https://picsum.photos/600/400?random=1',
    'data-ai-hint': 'salsa dancing',
    category: 'Ritmos Latinos',
    bookedStudents: 15,
  },
  {
    id: 'cls_hiphop_1',
    name: 'Hip-Hop Básico',
    description: 'Explora los fundamentos del hip-hop, desde el popping hasta el locking.',
    teacherId: 'usr_teacher_2',
    teacherName: 'Carlos Peña',
    schedule: 'Martes y Jueves, 19:00 - 20:00',
    duration: 60,
    maxStudents: 25,
    level: 'principiante',
    image: 'https://picsum.photos/600/400?random=2',
    'data-ai-hint': 'hip-hop dancing',
    category: 'Danza Urbana',
    bookedStudents: 22,
  },
  {
    id: 'cls_ballet_1',
    name: 'Ballet para Adultos',
    description: 'Nunca es tarde para aprender ballet. Mejora tu postura, flexibilidad y fuerza.',
    teacherId: 'usr_teacher_1',
    teacherName: 'Sofia Reyes',
    schedule: 'Sábados, 10:00 - 11:30',
    duration: 90,
    maxStudents: 15,
    level: 'principiante',
    image: 'https://picsum.photos/600/400?random=3',
    'data-ai-hint': 'ballet dancing',
    category: 'Danza Clásica',
    bookedStudents: 10,
  },
  {
    id: 'cls_bachata_2',
    name: 'Bachata Sensual Intermedio',
    description: 'Perfecciona tu técnica y aprende nuevas figuras de bachata sensual.',
    teacherId: 'usr_teacher_1',
    teacherName: 'Sofia Reyes',
    schedule: 'Viernes, 20:00 - 21:30',
    duration: 90,
    maxStudents: 18,
    level: 'intermedio',
    image: 'https://picsum.photos/600/400?random=4',
    'data-ai-hint': 'bachata dancing',
    category: 'Ritmos Latinos',
    bookedStudents: 18,
  },
  {
    id: 'cls_breakdance_1',
    name: 'Introducción al Breakdance',
    description: 'Aprende los movimientos básicos de toprock, footwork y freezes.',
    teacherId: 'usr_teacher_2',
    teacherName: 'Carlos Peña',
    schedule: 'Miércoles, 20:00 - 21:00',
    duration: 60,
    maxStudents: 15,
    level: 'intermedio',
    image: 'https://picsum.photos/600/400?random=5',
    'data-ai-hint': 'breakdancing',
    category: 'Danza Urbana',
    bookedStudents: 7,
  },
  {
    id: 'cls_contemporaneo_3',
    name: 'Danza Contemporánea Avanzada',
    description: 'Explora la expresión corporal y técnicas complejas de suelo y movimiento.',
    teacherId: 'usr_teacher_1',
    teacherName: 'Sofia Reyes',
    schedule: 'Martes y Jueves, 18:00 - 19:30',
    duration: 90,
    maxStudents: 12,
    level: 'avanzado',
    image: 'https://picsum.photos/600/400?random=6',
    'data-ai-hint': 'contemporary dance',
    category: 'Baile Moderno',
    bookedStudents: 10,
  },
];

export const MOCK_STUDENTS_PROFILES: StudentProfile[] = [
    { id: 'usr_student_1', name: 'Ana Morales', email: 'ana.morales@email.com', role: 'student', joinedDate: new Date('2023-01-15'), bookedClasses: 5 },
    { id: 'usr_student_2', name: 'Luis Garcia', email: 'luis.garcia@email.com', role: 'student', joinedDate: new Date('2023-02-20'), bookedClasses: 8 },
    { id: 'usr_student_3', name: 'Elena Torres', email: 'elena.torres@email.com', role: 'student', joinedDate: new Date('2023-03-10'), bookedClasses: 2 },
    { id: 'usr_student_4', name: 'Javier Solis', email: 'javier.solis@email.com', role: 'student', joinedDate: new Date('2023-04-05'), bookedClasses: 12 },
    { id: 'usr_student_5', name: 'Maria Rodriguez', email: 'maria.rodriguez@email.com', role: 'student', joinedDate: new Date('2023-05-21'), bookedClasses: 3 },
    { id: 'usr_student_6', name: 'David Martinez', email: 'david.martinez@email.com', role: 'student', joinedDate: new Date('2023-06-18'), bookedClasses: 7 },
    { id: 'usr_student_7', name: 'Laura Sanchez', email: 'laura.sanchez@email.com', role: 'student', joinedDate: new Date('2023-07-01'), bookedClasses: 1 },
];
